import type { Metadata } from "next";
import localfont from "next/font/local"
import "./globals.css";
import "easymde/dist/easymde.min.css";

const workSans = localfont({
  src: [
    {
      path: './fonts/WorkSans-Black.ttf',
      weight: '900',
      style: 'Black',
    },
    {
      path: './fonts/WorkSans-Bold.ttf',
      weight: '700',
      style: 'Bold',
    },
    {
      path: './fonts/WorkSans-ExtraBold.ttf',
      weight: '800',
      style: 'ExtraBold',
    },
    {
      path: './fonts/WorkSans-ExtraLight.ttf',
      weight: '100',
      style: 'ExtraLight',
    },
    {
      path: './fonts/WorkSans-Light.ttf',
      weight: '200',
      style: 'Light',
    },
    {
      path: './fonts/WorkSans-Medium.ttf',
      weight: '500',
      style: 'Medium',
    },
    {
      path: './fonts/WorkSans-Regular.ttf',
      weight: '400',
      style: 'Regular',
    },
    {
      path: './fonts/WorkSans-SemiBold.ttf',
      weight: '600',
      style: 'SemiBold',
    },
    {
      path: './fonts/WorkSans-Thin.ttf',
      weight: '200',
      style: 'Thin',
    },
  ],
  variable: '--font-work-sans'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={workSans.variable}
      >
        {children}
      </body>
    </html>
  );
}
